name: Precompute Hybrid News

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual runs

jobs:
  precompute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out data branch
        uses: actions/checkout@v3
        with:
          ref: data

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run precompute script
        run: node scripts/precompute_hybrid.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run
